    pipeline {
        agent any

         stages {
            stage('Build') {
                steps {
                    sh 'mvn clean package'
                }
            }
            stage('Docker') {
            agent{
            dockerfile {
            dir 'simple-springboot-app/'
            }
              }
                steps {
                    sh 'docker build -t arindamstingo/SpringApp:${BUILD_NUMBER} .'
                    sh 'docker login -u arindamstingo -p Sting1999@'
                    sh 'docker push arindamstingo/SpringApp:${BUILD_NUMBER}'
                }
            }

        }
    }
