pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage('Build') {
            steps {
                dir('simple-springboot-app') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Docker') {
            steps {
                dir('simple-springboot-app') {
                bat 'docker build -t arindamstingo/SpringApp:${BUILD_NUMBER} .'

                bat 'docker login -u arindamstingo -p Sting1999@'
                    bat 'docker push arindamstingo/SpringApp:${BUILD_NUMBER}'
                }
            }
        }
    }
}
